id: P003093
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ74547
  title: བྱང་ཆུབ་གཞུང་ལམ་དང་བླ་མ་ལྔ་བཅུ་པའི་རྣམ་བཤད།
  author: ''
  volumes:
    592c22418cee4d3eb2dc307920aa3848:
      image_group_id: I4CZ74549
      title: ''
      volume_number: 1
      total_pages: 450
      base_file: v001.txt
