id: I73D93030
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:31:45+00:00'
last_modified: '2022-06-07T17:30:43.639412+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74547
  title: བྱང་ཆུབ་གཞུང་ལམ་དང་བླ་མ་ལྔ་བཅུ་པའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CA44:
      image_group_id: I4CZ74549
      title: ''
      total_pages: 450
      order: 1
      base_file: CA44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
